
"use client";

import { Lightbulb } from 'lucide-react';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';

type SummaryCardProps = {
  summary: string;
  isLoading: boolean;
};

export function SummaryCard({ summary, isLoading }: SummaryCardProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Lightbulb className="h-6 w-6 text-primary" />
          <span>AI Summary</span>
        </CardTitle>
        <CardDescription>
          A quick overview generated by AI.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="space-y-2">
            <Skeleton className="h-4 w-[90%]" />
            <Skeleton className="h-4 w-[80%]" />
            <Skeleton className="h-4 w-[85%]" />
          </div>
        ) : (
          <p className="text-sm text-foreground/90">
            {summary}
          </p>
        )}
      </CardContent>
    </Card>
  );
}
